# Generated by Django 2.2 on 2019-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_auto_20190415_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='titration_liters',
        ),
        migrations.AddField(
            model_name='water',
            name='titration_liters',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
