# Generated by Django 2.2 on 2019-04-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_auto_20190416_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='titration_liters',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
