# Generated by Django 2.2 on 2019-04-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_auto_20190416_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='water',
            unique_together=set(),
        ),
    ]
