# Generated by Django 2.2 on 2019-04-16 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0008_auto_20190416_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date'),
        ),
    ]
